/* globals console,document,window,cordova */
var optionHash = {};
// These are defaults, the actual values of these options should be loaded from the persistence file at every page-load
optionHash["indexType"] = "Pictures";       // library folder shows pictures or details
optionHash["indexSort"] = "Author";         // library folder sorts on author-story or level-numberofwords
optionHash["messageWord"] = "On";           // option to show message that a word has been added to My Words
optionHash["messageToggle"] = "On";         // option to show message that you are toggling to another text or sound format
optionHash["programState"] = "Off";         // program is off by default
optionHash["programFreq"] = "Story";        // use story-group-level-total-corpus wordfreq to determine enough tests, !!!need to base this on root as well!!!
optionHash["programCorrect"] = "On";        // correct test only counts within schedule (plus margin)
optionHash["programDel"] = "Off";           // delete word automatically if enough tests, this is set to On if Program is turned on
optionHash["textFormat"] = "int";           // interlinear (int), pop-up interlinear (pnt) or pop-up (pop) as default
optionHash["fontType"] = "Arial";           // choose Font (urgh), Arial, Times New Roman, ehh
optionHash["fontSize"] = "18pt";            // formula adjusted to make interlinear font, line-heights correct for sizes 15/18/21/24/36
optionHash["linesizePlus"] = "0.0";
optionHash["sublinesizePlus"] = "0.0";
optionHash["sublinetopPlus"] = "0";
optionHash["interlinearColor"] = "dimgray";
optionHash["translationCurrent"] = "int";
optionHash["audioCurrent"] = "man";
optionHash["translationDefault"] = "int";
optionHash["audioDefault"] = "man";
optionHash["popPos"] = "Below";             // position of Pop up is below or above the mouseover or clicked word
optionHash["audioFormat"] = "man";          // manual, when going to next page, or all at once
optionHash["audioScroll"] = "Page";         // scroll with audio off, per page, per word (estimation) / later sentence, for now only Off or Page
optionHash["audioSpeed"] = "Normal";        // tweak speed of audio (for later version)
optionHash["wordsMark"] = "Off";            // mark my words in text (bold)
optionHash["wordsShow"] = "Off";            // show words in text, this only goes for pop-up interlinear format
optionHash["wordsLow"] = "Off";             // mark low freq words, depends on programFreq option (story, group, level, total or even corpus, ???and including root???)
optionHash["wordSort"] = "reminder";        // sorts words on reminder or words (alphabetical)
optionHash["testSched"] = "86400";          // schedule word practice off, every day, two days, week
optionHash["testIncr"] = "1";               // schedule increment, default none, or 1 (so if interval is day, every day)
optionHash["testNumber"] = "21";            // max number of tests before word is deleted or not asked in word cards (max 21)
optionHash["testCeiling"] = "0";            // number of tests where increment stops and only last interval is added each time to avoid ridiculous and useless lengths
optionHash["testFlash"] = "default";        // in-list (Default) or single flash card practice
optionHash["testRemind"] = "25";            // my word reminder message pop-up off, at 10 words to practice, 25 words to practice, 50 words, or 100 words
optionHash["testMargin"] = "0.25";          // schedule percentage margin allowed, this helps if number of correct tests matters and with daily schedule you are an hour early, for example
optionHash["testAutopen"] = "Off";          // auto open new card (eh leaves little room for ponder)
optionHash["reminder1"] = "86400";          // Reminder number 1 (always equals testSched)
optionHash["reminder2"] = "86400";          // Reminder number 2 (equals testSched times testIncr)
optionHash["reminder3"] = "86400";          // Reminder number 3 (equals reminder number 2 times testIncr)
optionHash["reminder4"] = "86400";          // Reminder number 4 (etc. we calculate them when changing testSched or testIncr)
optionHash["reminder5"] = "86400";          // Reminder number 5
optionHash["reminder6"] = "86400";          // Reminder number 6
optionHash["reminder7"] = "86400";          // Reminder number 7
optionHash["reminder8"] = "86400";          // Reminder number 8
optionHash["reminder9"] = "86400";          // Reminder number 9
optionHash["reminder10"] = "86400";         // Reminder number 10
optionHash["reminder11"] = "86400";         // Reminder number 11
optionHash["reminder12"] = "86400";         // Reminder number 12
optionHash["reminder13"] = "86400";         // Reminder number 13
optionHash["reminder14"] = "86400";         // Reminder number 14
optionHash["reminder15"] = "86400";         // Reminder number 15
optionHash["reminder16"] = "86400";         // Reminder number 16
optionHash["reminder17"] = "86400";         // Reminder number 17
optionHash["reminder18"] = "86400";         // Reminder number 18
optionHash["reminder19"] = "86400";         // Reminder number 19
optionHash["reminder20"] = "86400";         // Reminder number 20
optionHash["reminder21"] = "86400";         // Reminder number... 21!
// End of options